automation:
  - alias: System Travis Build Status
    trigger:
      - platform: state
        entity_id: sensor.travis_build_status
        from: "started"
        to: "failed"
    action:
      - service: notify.ios_johns_iphone
        data_template:
          message: >
            Travis build failed! {{ "\uD83E\uDD2C" }}
          data:
            url: https://travis-ci.com/jbrody17/home-assistant-config

  - alias: System Travis Build Passed
    trigger:
      - platform: state
        entity_id: sensor.travis_build_status
        from: "started"
        to: "passed"
    action:
      - service: notify.ios_johns_iphone
        data_template:
          message: >
            Travis build passed! {{ "\uD83D\uDC4D" }}
          data:
            url: https://travis-ci.com/jbrody17/home-assistant-config
      - service: hassio.addon_start
        data:
          addon: core_git_pull

sensor:
  - platform: rest
    resource: https://api.travis-ci.com/builds
    headers:
      Travis-API-Version: 3
      Authorization: !secret travis_API_KEY
    value_template: "{{ value_json.builds[0].state }}"
    name: "Travis Build Status"
  # - platform: travisci
  #   api_key: