homeassistant:
  customize:
    switch.xbox_360:
      friendly_name: Xbox 360
      icon: mdi:xbox
    switch.apple_tv:
      friendly_name: Apple TV
      icon: mdi:apple
    switch.computer:
      friendly_name: Computer
      icon: mdi:desktop-classic
    switch.record_player:
      friendly_name: Record Player
      icon: mdi:record-player
    switch.speakers:
      friendly_name: Speakers
      icon: mdi:amazon-alexa

remote:
  - platform: harmony
    name: Living Room
    host: 192.168.1.133

switch:
  - platform: template
    switches:   
        # Apple TV Activity
        apple_tv:
          value_template: "{{ is_state_attr('remote.living_room_3', 'current_activity', 'Watch Apple TV') }}"
          turn_on:
            service: remote.turn_on
            data:
              entity_id: remote.living_room_3
              activity: 'Watch Apple TV'
          turn_off:
            service: remote.turn_on
            data:
              entity_id: remote.living_room_3
              activity: 'PowerOff'

        # Xbox 360 Activity
        xbox_360:
          value_template: "{{ is_state_attr('remote.living_room_3', 'current_activity', 'Games') }}"
          turn_on:
            service: remote.turn_on
            data:
              entity_id: remote.living_room_3
              activity: 'Games'
          turn_off:
            service: remote.turn_on
            data:
              entity_id: remote.living_room_3
              activity: 'PowerOff'
        
        # Computer Activity
        computer:
          value_template: "{{ is_state_attr('remote.living_room_3', 'current_activity', 'Computer') }}"
          turn_on:
            service: remote.turn_on
            data:
              entity_id: remote.living_room_3
              activity: 'Computer'
          turn_off:
            service: remote.turn_on
            data:
              entity_id: remote.living_room_3
              activity: 'PowerOff'
        
        # Speakers Activity
        speakers:
          value_template: "{{ is_state_attr('remote.living_room', 'current_activity', 'Listen to Music') }}"
          turn_on:
            service: remote.turn_on
            data:
              entity_id: remote.living_room_3
              activity: 'Listen to Music'
          turn_off:
            service: remote.turn_on
            data:
              entity_id: remote.living_room_3
              activity: 'PowerOff'
        
        # Record Player Activity
        record_player:
          value_template: "{{ is_state_attr('remote.living_room', 'current_activity', 'Record') }}"
          turn_on:
            service: remote.turn_on
            data:
              entity_id: remote.living_room_3
              activity: 'Record'
          turn_off:
            service: remote.turn_on
            data:
              entity_id: remote.living_room_3
              activity: 'PowerOff'
    
sensor:
  - platform: template
    sensors:
      harmony_activity:
        value_template: >
          {% if is_state("remote.living_room_3", 'on') %}
            {{ states.remote.living_room_3.attributes.current_activity }}
          {% else %}
            PowerOff
          {% endif %}