sensor:
- platform: plex

sensor:
- platform: template
  sensors:
    plex_living_room_playing:
      friendly_name: 'Currently Playing on Plex - Living Room'
      value_template: "{{ state_attr('media_player.living_room_2', 'media_content_type') }}"

- platform: plex_recently_added
  token: !secret plex_token
  host: 192.168.1.5
  port: 32400
  ssl: true
  max: 5
  section_types:
  - movie
  - show

media_player:
- platform: plex
  entity_namespace: 'plex'
  include_non_clients: true
  scan_interval: 5
  show_all_controls: false
  use_custom_entity_ids: true
  use_episode_art: true
  remove_unavailable_clients: true
  client_remove_interval: 10